Add tui stuff to executable

diff --git a/Bakery b/Bakery
--- a/Bakery
+++ b/Bakery
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
-# Launch DIR/gui.py or DIR/tui.py when --gui or --tui is passed
+# Launch DIR/gui.py, DIR/tui.py, or DIR/tui.py with --simple when --gui, --tui, or --simple is passed
 
 ui=""
+extra_args=()
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)" # to be changed to future install dir
 
 if [[ $script_dir == "/usr/bin" ]]; then
@@ -15,6 +16,11 @@ while [[ $# -gt 0 ]]; do
             ui="${1#--}"
             shift
             ;;
+        --simple)
+            ui="tui"
+            extra_args+=("--simple")
+            shift
+            ;;
         *)
             echo "Error: Unknown argument $1"
             exit 1
@@ -25,12 +31,13 @@ done
 if [[ $ui == "gui" || $ui == "tui" ]]; then
     script_name="bakery-$ui.py"
     if [[ -f "$script_dir/$script_name" ]]; then
-        python "$script_dir/$script_name"
+        python "$script_dir/$script_name" "${extra_args[@]}"
     else
         echo "Error: bakery-$ui is not installed"
         echo "Please install bakery-$ui with 'sudo pacman -S bakery-$ui'"
         exit 1
     fi
 else
-    echo "Error: Unknown UI $ui"
+    echo "Error: No UI specified."
+    exit 1
 fi
